name: Deploy aji_tkhdem

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          docker compose down
          docker compose up -d --build